### PR TITLE
Dynamic Updates to Modal Box

### PR DESCRIPTION
**Pull request by alfredbrannare**
This merge introduces dynamic functionality to the modal box. It will:
- Update the room title, time slots, and participant range dynamically.
- Send a POST request to the API with the challenge and input values.

Will merge **book-room-modal-box** to main once these are merged to try if it works.

https://github.com/user-attachments/assets/fa460c70-67f6-4825-abfc-9bfc8b57c71e

### CODE REVIEW

**Review by Paajt — APPROVED** [review]
Great job with working functionality! Ok to merge for me!

**Comment by NordicNomadicLife** [comment]
looks good for me awsome work, good to merge for me

**Comment by itsJoel59** [comment]
Looking GREAT and functional, OK to merge

**Comment by Emilyempa** [comment]
Looks awsome! Good Job and very nice with a recording to show what you have done

**Review by Emilyempa — APPROVED** [review]

**Pull request merged**
