### PR TITLE
Load challenge data

### PR DESCRIPTION
**Pull request by Emilyempa**
Fetch img, title, participants, description and type,  add bookingbutton
Starting to build cards

### CODE REVIEW

**Comment by alfredbrannare** [comment]
Looks nice! 

Okay to merge on my side.

**Comment by itsJoel59** [comment]
Looking good, okay to merge!

**Review by Paajt — APPROVED** [review]
Looks good! 👍 
Okay for me to merge! 🎆

**Comment by NordicNomadicLife** [comment]
looks good, okay from my side to merge!

**Comment by Emilyempa** [comment]
Awsome that everybody was ok with this, I will merge and then everyone can fetch new main

**Pull request merged**
